function fun(){
    var k= document.getElementById("music");
k.play();
k.loop=true;
var praise= ["you are very cute",
"your smile kills me",
"Your strength in the face of obstacles is amazing",
"Your beautiful smile brightens my day",
"Your eyes are beautiful because they are filled with kindness and intelligence",
"Your intelligence and conviction are powerful",
"I enjoy your unique perspective",
"I’m charmed by your sense of humor",
"The kindness you show to everyone is inspiring",
"You make a huge difference in the lives of those around you",
"I want to be like you",
"No matter what you wear, you always look fantastic",
"I love spending time with you",
"Your encouragement makes me feel like I can change the world",
"Your presence warms the coldest heart",
"I have the most fun when I’m with you",
"Your voice adds cheer to the most dreary day",
"Your creativity and artistic ability blow me away",
"I’ve never met anyone as trustworthy and honest as you",
"I like how you know exactly who you are and what you want from life",
"You’ve given me a whole new perspective on life. Thank you!!!",
"The sound of your laughter makes me feel like I just won a million dollars",
"I love the way you take care of me, You are such a selfless person",
"Your style is amazing, and I wish I was as fashionable as you",
"You make me want to be better and better every day",
"I’m fascinated by your lips because they always say the most amazing things and outline the most beautiful smile",
"You are like a dazzling diamond that I will treasure always",
"When I’m not around you, I’m thinking about you",
"I’d rather spend time with you than anyone in the world",
"I feel like I’m on vacation from all the world’s troubles when we’re together",
"You put a lot of effort into caring for others. I appreciate you",
"You are my favorite person to talk to. Thank you for listening with a caring heart",
"I trust and value your opinion. You make insightful observations",
"Whenever I see you, the clouds roll away and birds start singing",
"I can’t imagine life without you",
"I can’t take my eyes off the beauty you radiate with that confident smile",
"Your confidence is attractive",
"I’m sorry that it took so long for us to meet",
"I’m drawn in by your warm, intelligent conversation",
"I like how you really know what you want, and how you are fearless when you go about getting it",
"The sight of you in that dress is stunning",
"The first thing I noticed about you is your elegance",
"I like how your spur-of-the-moment ideas keep me on my toes",
"Your energy and bold spirit make me want to be with you forever",
"No matter what you encounter, you are always classy",
"Your loveliness takes my breath away",
"You look professional and polished",
"Your flamboyant personality excites me",
"You are just the spark my battery needed",
"I am exhilarated by your energy and passion",
"Your flawless intuition astounds me",
"Your humility and grace cause people to take notice",
"You have brought great joy into my life",
"I love how you make ordinary events romantic",
"I could listen to your heartwarming stories all day",
"Your feistiness and zest for life motivate me",
"If someone wrote a book about you, it would be a bestseller",
"The sight of your beautiful face framed by your soft hair is hard to resist",
"I am comforted by your hugs",
"When I focus on you, the big picture is revealed",
"If life was a river, I’d choose to paddle alongside you",
"There is an overwhelming peace when I’m in your presence",
"You always know the perfect thing to say",
"Your beauty is enticing",
"Your taste is impeccable",
"Thanks for always keeping your cool",
" I’m so glad we belong to each other",
"You have blessed my life with peace and love",
"You make loving you as simple as breathing",
"To be with you is to be alive",
"No matter who is in the room, I always find myself staring at you",
"In a world of background noise, you are a cheerful melody",
"I can never put into words how much you mean to me. I love you more deeply each day",
"A day without you is too long. You are like a shade tree in the desert",
"My eyes can’t wait to see you each day, I want your smily face forever",
"Wherever you are is where I want to be",
"You motivate me to exercise. Who wouldn’t want to work out next to your flawless figure?",
"Your love is like an orchard: sweet, sustaining, and beautiful",
"Your enthusiasm and passion for life is contagious",
"All my dreams came true when I met you",
"You are always the highlight of my day",
"Holding your hand is the best medicine",
"I love how your eyes outsparkle your diamond earrings",
"I have never been more proud to call you my girlfriend/friend/wife",
"You make each day a celebration",
"I can’t wait to see what adventures are in our future. You make everything fun",
"When you sing, my ears are happy, but my heart is overjoyed",
" No matter who I may meet in life, no one will mean as much to me as you do",
"You have amazing vibes, and I want to be with you forever",
"Your strength and determination help me believe in myself"
];
document.getElementById("para").innerHTML = praise[Math.floor(Math.random()*90)]+'      ...';
console.log(praise.length);
}