function funny(){
    var k= document.getElementById("music");
k.play();
k.loop=true;
var praise= [
"I am so lucky to have you in my life",
"I appreciate everything that you do for me",
"You are awesome",
"You are such an incredible guy",
"You are brilliant",
"You are amazing",
"I am so glad that you are my friend",
"You are the strongest guy I know",
"You are so thoughtful",
"I have so much respect for you",
"You put a lot of thought into everything that you do",
"You are the best man out there",
"You are so powerful",
"You are so big and strong",
"You are so irresistibly charming",
"You have an amazing energy",
"You make me a better person",
"You are such an inspiration to me",
"I look up to you so much",
"I really appreciate everything that you do",
"Your cooking was delicious",
"You make me happy",
"You are a rock star",
"You are incredible",
"You make me so proud",
"I am proud to know you",
"You are the funniest guy I know",
"You are so handy",
"You are so good at fixing things",
"You are so smart",
"You are the strongest man that I have ever met",
"You always know how to make me break into a smile",
"I love that you know how to cook",
"Any woman would be lucky to have you",
"I always feel safe when I am around you",
"It is an honor to know you",
"You are so selfless",
"You have a strong handshake",
"I love talking to you",
"You are very insightful",
"You are always so upbeat",
"I love your positive energy",
"You are always so energetic",
"You are such an easygoing guy",
"You are so artistic",
"I admire your candor",
"I admire your strong sense of confidence",
"You are always so reasonable",
"I wish I was as patient as you",
"I love your persistence. You always refuse to give up",
"Your strong sense of motivation is something that I have always admired",
"You are very athletic",
"You are always quick on your feet",
"You are a good dancer",
"You have good rhythm",
"You are a quick thinker",
"You seem to know how to fix everything",
"You are so easy to have a conversation with",
"I love that I can just be myself with you",
"You tell the funniest jokes",
"I love spending quality time with you",
"I really enjoy our time together",
"I really enjoy our talks",
"You are a really great person to talk to",
"You are so easy to talk to",
"You always have such great ideas",
"Anyone would be lucky to have you on their team",
"The world would be a better place if there were more people like you",
"You always set a great example for other people",
"You are hands down the most attractive guy in the world to me",
"You are so brave",
"You are so funny",
"You really know how to make me laugh",
"You have such a kind heart",
"You are just irresistible",
"My parents love you",
"My friends really like you",
"You are such a hard worker",
"I can already tell that you are going places",
"You are so chivalrous",
"You really know how to cook",
"I love how genuine you are",
"I know that I can trust you",
"It is so easy to trust you",
"You have a beautiful soul",
"I love how passionate you are about the work that you do",
"I love how dedicated you are to your job",
"You have such strong principles. I really admire that about you",
"You have such big, strong arms",
"You are so driven",
"I like that you tend to think outside the box",
"You have great smile",
"You are one of the good guys",
"I love how smart you are",
"You are my favorite weakness",
"I love how openminded you are",
"I love that you never judge me",
"You make me happy in a way that I have never felt before",
"I am so thankful that I met you",
"I feel so comfortable around you. You are like a pair of comfy sweatpants",
"You have a wonderful personality",
"I could not live without you",
"I love seeing you smile",
"What a smart observation you made",
"You are really good at noticing every little detail",
"Talking to you makes my day",
"You are a very interesting guy",
"I feel like I could talk to you for hours and hours without ever getting bored of the conversation",
"Is that a new cologne? You smell really good",
"Your smell makes me butterflies",
"Those are nice shoes you have on",
"I love that you can laugh at yourself",
"I love how much you value honesty",
"You are wonderful, even on a bad day",
"You are my best adventure",
"You make my heart soar",
"You are such a classy guy",
"You are so athletic",
"You are so suave",
"You are so smooth",
"You are so adventurous",
"You have so much courage",
"You are such an innovative person",
"You are one of the most intelligent people that I have ever met",
"You are so generous",
"You are such a gentle soul",
"You are such a helpful person",
"You are wise beyond your years",
"I love your enthusiasm",
"You are, without a doubt, an honorable man",
"I love how optimistic you always are",
"You are so friendly to everyone that you meet",
"Your smile is proof to me that the best things in life are free",
"You are so cool",
"I love how confident you are",
"You are such an insightful person",
"You are so down to earth",
"I love how much you care about things",
"You have such a warm heart",
"Being with you is fun",
"I enjoy spending time with you",
"You are so understanding",
"You have such an energetic personality",
"you are the most responsible guy I know",
"love your sense of creativity",
"ou are so friendly and approachable",
"Your determination is admirable",
"You are so outgoing",
"You are so full of integrity",
"I love that you are always teaching me something new",
"You are such a dependable guy",
"You are so reliable",
"I trust you with all my heart",
"You are not like all the other guys and that is what I like about you",
"You are so good at what you do",
"You are a true friend",
"Your smile can light up the whole room",
"I know that I can always turn to you",
"Your patience is one of your bests qualities",
"You are so witty",
"Your charm is immeasurable",
"I love how flexible you are",
"You have such a good eye for detail",
"You are incredibly observant",
"I love your enthusiasm",
"I like how genuine you are",
"You are such a motivated individual",
"You are such a strong person",
"You are my calm during the storm",
"You look so handsome, even when you have just woken up and your hair is all messy",
"The ladies can’t seem to take their eyes off of you",
"You are classically handsome",
"You are really, really, really, ridiculously good-looking",
"You look so handsome in that suit",
"You have such a great smile",
"You have really nice eyes",
"I really like your style",
"You are so cute",
"You have such impeccable style",
"You look hot",
"You have beautiful eyes",
"You look great today",
"Have you lost weight recently? You look really good",
"You look really handsome",
"You are looking good",
"You are such a hunk",
"I like your hair",
"Your arms look so good in that shirt",
"You could be a model",
"You have a nice butt",
"You must be really hitting the gym these days",
"Are you sure you have never modeled before ?",
"You have really nice teeth",
"You have nice lips",
"You have nice abs",
"I could get lost in your eyes",
"You are cuter than any celebrity out there",
"You have great hair",
"You really look in shape",
"Did you get a haircut? It looks really good on you",
"Are those new glasses? You look nice in them",
"You look really good today",
"You are looking dapper today",
"You are quite stylish",
"Those glasses really bring out your eyes",
"Have you been working out ? ",
"That color looks really good on you",
"That shirt really brings out your eyes",
"That is a nice beard",
"Your skin is really nice. What do you use for it ? ",
"You are such a good worker",
"You are such a strong leader",
"I know that you can accomplish anything that you put your mind to",
"I really believe in you",
"You are so talented",
"I am so proud of you",
"You have such a great mind for business",
"You have a great work ethic",
"You are a master of innovation",
"You are so professional",
"You are a real go-getter",
"You are a born leader",
"You have such a way with words",
"You are such an eloquent speaker",
"When you talk, the whole room listens",
"I love that you go out of your way to help others",
"You are such an attentive guy",
"You are a very efficient worker",
"You are a hardworking guy",
"You have great communication skills",
"Your work is always exceptional",
"Your latest work was exemplary",
"I really admire your professionalism",
"You are a great problem solver",
"When you have something to say, you know how to make people listen",
"You make me weak in the knees",
"I still get butterflies in my stomach when I am with you",
"When I am with you, I feel like a giddy teenager all over again",
"When you listen to me, I feel so heard and so loved",
"You look as good as the day we met, maybe even better",
"I love feeling your big, strong arms around me",
"You know how to turn me on",
"You know exactly what to say to make me blush",
"I love being in your arms",
"You always make me feel so beautiful",
"I could lay like this with you forever",
"You make me so happy",
"You know how to make me feel like a lady",
"You can be so romantic",
"You know exactly how to be a gentleman",
"I feel so safe in your arms",
"You are my knight in shining armor",
"This was the best date ever",
"You really know how to make me feel loved",
"You are my perfect man",
"You chose the best place to have a date",
"I love it when you wrap your arms around me",
"I love that you listen to me",
"You really know how to make me feel like a lady",
"I love that you respect me",
"I love spending time with you",
"I love that you kiss me every day",
"I love that you hug me for no reason",
"I am having such a great time on this date with you",
"You are so unbelievably sexy to me",
"I love how it feels when you kiss me",
"I love feeling your arms wrapped around me",
"I love the feeling of my hand in yours",
"I love it when we are out somewhere and you will just reach out for my hand",
"You are my favorite person to spend time with",
"You are always so good at giving me the best advice",
"I feel safe when you hold me tight",
"You smell great",
"What are you swearing? You smell so good",
"I love how manly your voice is",
"You always know the right thing to say",
"You have such a comforting voice",
"You always make me feel so comfortable and at ease",
"You are cuter than Channing Tatum",
"You are hotter than Brad Pitt",
"You are going to make such a great dad",
"You are such a good dad",
"You are so great with the kids",
"You are such a good father",
"Thank you for leading our family",
"You are superdad",
"You are such a great provider for our children",
"You are such a loving father",
"The kids love you so much",
"You are the best dad that I have ever seen",
"I can tell that you would do anything for your kids",
"I love how you always put the kids first",
"You are such a loving father",
"It is great how involved you are with the kids",
"Your kids love you so much",
"You are so devoted to your kids",
"I can see how much your kids adore you",
"Your kids really look up to you",
"Your kid really sees you as a role model",
"I can tell that your kid wants to be just like you",
"Thank you for being such a dedicated father",
"Those are your kids? You look so young, are you sure you are not their older brother ? ",
"You are such a supportive husband. Thank you for always having my back",
"Thank you for always being attentive to my needs. You are a good husband",
"Thank you for taking care of our family",
"After all of these years that we have been together, you still know how to make me feel like the most special person in the world.  That is why you are the perfect husband for me",
"Dear husband, thank you for your endless loyalty and for always being by my side through the good times and the bad times",
"I am incredibly blessed to have you as my husband",
"I am so lucky to be married to you",
"Thank you for being such a great husband to me. Words alone cannot express how happy you make me",
"It is such an honor to be your wife",
"Every day that I wake up, I am thankful that you are my husband"
];
document.getElementById("para").innerHTML = praise[Math.floor(Math.random()*312)]+'      ...';
console.log(praise.length);
}